import type { ModelPreset, ModelId } from "../types";
export const models: ModelPreset[] = [
  {
    id: "qwen38-dense",
    name: "Qwen3.8-27B",
    family: "dense",
    hiddenSize: 5120,
    headDim: 256,
    qHeads: 24,
    kvHeads: 4,
    layerTypes: [
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
    ],
    ffnSize: 17408,
    sharedExperts: 0,
    linearKeyHeads: 16,
    linearValueHeads: 48,
    linearHeadDim: 128,
    sources: [
      {
        id: "Qwen/Qwen3.8-27B",
        title: "Qwen/Qwen3.8-27B 官方配置",
        url: "https://huggingface.co/Qwen/Qwen3.8-27B/blob/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json",
        revision: "1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0",
        checkedAt: "2026-10-04",
      },
    ],
  },
  {
    id: "qwen36-moe",
    name: "Qwen3.6-35B-A3B",
    family: "moe",
    hiddenSize: 2048,
    headDim: 256,
    qHeads: 16,
    kvHeads: 2,
    layerTypes: [
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
      "linear_attention",
      "linear_attention",
      "linear_attention",
      "full_attention",
    ],
    ffnSize: 512,
    expertCount: 256,
    activeExperts: 8,
    sharedExperts: 1,
    linearKeyHeads: 16,
    linearValueHeads: 32,
    linearHeadDim: 128,
    sources: [
      {
        id: "Qwen/Qwen3.6-35B-A3B",
        title: "Qwen/Qwen3.6-35B-A3B 官方配置",
        url: "https://huggingface.co/Qwen/Qwen3.6-35B-A3B/blob/995ad96eacd98c81ed38be0c5b274b04031597b0/config.json",
        revision: "995ad96eacd98c81ed38be0c5b274b04031597b0",
        checkedAt: "2026-10-04",
      },
    ],
  },
  {
    id: "teaching",
    name: "缩小教学结构",
    family: "dense",
    hiddenSize: 128,
    headDim: 32,
    qHeads: 4,
    kvHeads: 2,
    layerTypes: [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
    ],
    ffnSize: 352,
    linearKeyHeads: 0,
    linearValueHeads: 0,
    linearHeadDim: 0,
    sources: [],
  },
];
export const getModel = (id: ModelId) =>
  models.find((model) => model.id === id)!;
